### ISSUE TITLE
ModuleNotFoundError: No module named 'diffusion_net'

### ISSUE THREAD

**Issue by linhcentrio** [miccunifi/ScanTalk#1]
![image](https://github.com/user-attachments/assets/2a3cab7d-b3e5-4f7e-9e7b-f114b56079e2)

**Comment by FedeNoce** [comment]
Hi, 

Thank you for your interest in our repo.

The `diffusion_net` module is already included in the `models` folder, so there's no need to install it separately. To import it correctly, please make sure you're running the script from within the `src` folder.

Best,  
Federico
