### ISSUE TITLE
Please share your dataset folder to run demo.py

### ISSUE THREAD

**Issue by linhcentrio** [miccunifi/ScanTalk#2]
![image](https://github.com/user-attachments/assets/ba1575f7-66cc-4e03-a8d7-fa19df60fa12)

**Comment by FedeNoce** [comment]
Hi, 

Thank you for your interest in our repo. We are currently in the process of getting permission from the dataset owner to release our modified version. Once we have approval, we will make the dataset available.

In the meantime, to run the demo, you can use any audio snippet and any 3D face that is aligned with the `FLAME_samples.ply` mesh found in the `examples` folder. There are also some example files included in that folder.

Best,  
Federico
