### ISSUE TITLE
HELP!!! Can I get the pre-trained model?

### ISSUE THREAD

**Issue by zhongshijun** [miccunifi/ScanTalk#4]
Thank you for open-sourcing the code. However, I encountered an issue. When trying to download the pre-trained model, Google Drive prompts that I don't have access permission.

**Comment by FedeNoce** [comment]
I shared with you the pretrained models

**Comment by FedeNoce** [comment]
I shared with you the pretrained models

**Comment by zhongshijun** [comment]
Thank you

**Comment by ljijj** [comment]
Thanks for your work. I face same th equestion, could you share me the the pre-trained model?
